### ISSUE TITLE
Connect Reference to Referenced Resource

### ISSUE THREAD

**Issue by azaroth42** [iiif-prezi/iiif-prezi3#35]
In order to have a Manifest in a Collection, the Collection should have a Reference to the Manifest, not the full Manifest resource.
This works as expected, hooray!

But ... if the referenced resource is modified, such as to change its label, then the Reference isn't updated.

e.g.

```
m = Manifest(label="1")
c = Collection()
c.items = [m]
m.label = {"en": ["2"]}
print(c.items[0].label) # --> 1
print(m.label) # --> 2
```

**Comment by glenrobson** [comment]
We will have to update the docs but this is due to pydantic doing a deep copy of the resource rather than just doing a reference. If you updated the label on c.items[0].label it would work OK. 

Note this affects all instances of class setters. We might also have to check the helpers to make sure they return the correct reference. For this specific usecase there is a helper method:  

https://github.com/iiif-prezi/iiif-prezi3/blob/main/iiif_prezi3/helpers/collection_add_methods.py

Pydantic has an option `copy_on_model_validation` which we could turn on. It defaults to `true`. 

Related to: https://github.com/samuelcolvin/pydantic/issues/1246

**Comment by giacomomarchioro** [comment]
https://github.com/iiif-prezi/iiif-prezi3/pull/50 should fix it and it apparently doesn't cause any collateral damage :-) I have added a test to check that this behaviour is maintained.
