### ISSUE TITLE
Make tox use the requirements from setup.py

### ISSUE THREAD

**Issue by digitaldogsbody** [iiif-prezi/iiif-prezi3#98]
This will ensure it is always testing against the versions we require for the package.

Some guidance here: https://stackoverflow.com/questions/29870629/pip-install-test-dependencies-for-tox-from-setup-py

**Comment by rlskoeser** [comment]
FWIW, I recently worked on a python package where we were using `setup.cfg` (which I gather is the new recommendation instead of setup.py; we have a minimal setup.py for backwards compatilbility). I figured out how to configure tox in the same config file and share configuration for python dependencies; you can see the result here https://github.com/dh-tech/undate-python/blob/develop/setup.cfg  

I don't think it's doing exactly what you want, but it might be a step in the right direction — and if you figure out how to take it even further to make the versions match, I'd love to see it.

**Comment by giacomomarchioro** [comment]
I also start using it and I find it very handy especially if you want to offer also command-line interfaces. The documentation is a little bit poor, but if I remember well you can refer to a variable inside the `.cfg` file so we could put everything in there and then share the common variables.  This module  https://github.com/asottile/setup-py-upgrade should help to make the conversion from `setup.py` to `setup.cfg`.

**Comment by digitaldogsbody** [comment]
Resolved this by changing tox to build the sdist of the package when run, which has the effect of installing the dependencies in the tox virtualenv. Combined with the `extras` flag in the linting section to install flake8 etc, this seems to have resolved the issue, and tox now uses the same dependencies as the main package.
